### ISSUE TITLE
Outline doesn't move on margin change

### ISSUE THREAD

**Issue by rpominov** [webstudio-is/webstudio-designer#625]
1. Select a Box on canvas
2. Change its margin from style panel
3. Box moves but the selected instance outline does not move

**Comment by TrySound** [comment]
I can check

**Comment by rpominov** [comment]
Would be great

**Comment by taylornowotny** [comment]
Is this what you're talking about?

https://user-images.githubusercontent.com/86495896/207951671-b01e9cdb-ced4-4681-998b-6a3655891725.mov

If so, I don't think the outline of an element should include margin. We should outline elements where the border would appear, and borders are not affected by margin.

**Comment by kof** [comment]
Seems like we already fixed it on main https://share.descript.com/view/s5OvybNlW3Y

**Comment by rpominov** [comment]
Not fixed. Worked for you because changing margin also changed size in your case.

The problem is that outline does not update if you move component somehow without changing size. Many ways to do this:

1. Change margin
2. Change float (also shown in video)
3. Change top/left with position: absolute
4. etc.

https://user-images.githubusercontent.com/825702/208041669-80a88c3c-0edf-4d60-9ead-7f935b614bcb.mov

**Comment by TrySound** [comment]
Looks like fixed here https://github.com/webstudio-is/webstudio-designer/pull/637

**Comment by kof** [comment]
@TrySound did you try @rpominov's repro?

**Comment by TrySound** [comment]
Yes. Why? You reproduced something?

**Comment by rpominov** [comment]
Yes. Almost fixed. But still reproducible when you scrub:

https://user-images.githubusercontent.com/825702/208363661-79d4b336-66e4-44bd-8d82-97a8d1efea87.mov

**Comment by rpominov** [comment]
BTW, none of this seem to be needed now (unless you scrub): https://github.com/webstudio-is/webstudio-designer/blob/bb0e3153387f680a37fd7e1e6a4451888e70db94/apps/designer/app/canvas/features/wrapper-component/selected-instance-connector.ts#L33-L69

**Comment by TrySound** [comment]
Maybe hide outline when preview styles are send? We have more and more of cases where frequently changing values make outline laggy

**Comment by kof** [comment]
Yeah, I agree we should hide it, here is another issue for hiding it when resizing canvas, feel free to add a case there or to change it right away

https://github.com/webstudio-is/webstudio-designer/issues/638

**Comment by taylornowotny** [comment]
Wouldn't it be better to fix the lag rather than hide outlines?

When a user is re-sizing something or adding margin, especially while scrubbing, the outlines show the user the effect of the change they are making. The changes might not otherwise be visible. Seems to me like this would defeat the utility of scrubbing since you can't see your changes during the scrub.

**Comment by TrySound** [comment]
It's latency of sending events to iframe and getting response with compute size back. Not sure if there is a solution for this.

**Comment by taylornowotny** [comment]
Ok if there's nothing we can do about it then it's not an issue.

I checked what Webflow is doing and they remove outlines as well. They show an arrow when adjusting margin/padding but it lags.

**Comment by kof** [comment]
The problem with the outline rendered on top of the element separately, its not even the latency, its just the fact that it needs to be updated separately and at with interactions like scrub there is always a tiny async movement, which makes you feel its a little off.
